### PR TITLE
Setup Authentication and Authorization 

### PR DESCRIPTION
**Pull request by ekrresa**
## Description
In this PR, I created routes for users to signup and login. Both routes returns a token containing the user's `Id, role, and roleId`. On login, the user's role is verified and saved in the token.

I also added middleware that checks the roles of all users and takes appropriate actions.

I also made changes to the DB structure so running the new migrations will be destructive.

Fixes #23  #3 

## How Has This Been Tested?
I was able to signup and login with the routes. Will write tests later

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ekrresa** [comment]
Tests are failing because we've not setup a database for tests. Also codacy appears to be drunk.

**Comment by vector-ok** [comment]
Great job so far. 
Problem is with that url undefined. It expects a string as shown. 
If we merge it, we'll still run into the same problem or more when merging our Develop branch into Master.  And will still be shown when our code is tested after finishing our product.

I know our secrets must remain hidden but I think we somehow have to find a way to resolve it.
Is there no way to rework the code so that we only have 
export const sequelize
on that Export instead of 
export const sequelize = new....

**Comment by Douglasokolaa** [comment]
> Tests are failing because we've not setup a database for tests. Also codacy appears to be drunk.

IF you have VS CODE editor you need to install [EditorConfig for VS Code](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) then before push you commit changes you need right-click and select format code in edited files to avoid Codeacy issues. lol

**Comment by Douglasokolaa** [comment]
> Great job so far.
> Problem is with that url undefined. It expects a string as shown.
> If we merge it, we'll still run into the same problem or more when merging our Develop branch into Master. And will still be shown when our code is tested after finishing our product.
> 
> I know our secrets must remain hidden but I think we somehow have to find a way to resolve it.
> Is there no way to rework the code so that we only have
> export const sequelize
> on that Export instead of
> export const sequelize = new....

can you set secrets ?

**Comment by vector-ok** [comment]
> > Great job so far.
> > Problem is with that url undefined. It expects a string as shown.
> > If we merge it, we'll still run into the same problem or more when merging our Develop branch into Master. And will still be shown when our code is tested after finishing our product.
> > I know our secrets must remain hidden but I think we somehow have to find a way to resolve it.
> > Is there no way to rework the code so that we only have
> > export const sequelize
> > on that Export instead of
> > export const sequelize = new....
> 
> can you set secrets ?

It comes with most backend work. I could try if its the issue.

**Review by Douglasokolaa — APPROVED** [review]
good work

**Review by vector-ok — APPROVED** [review]
Nicely done.

**Pull request merged**
